name: lib2
version: 0.2.0.0
dependencies:
  - base >= 4.8 && < 5
  - lib1
library:
  source-dirs: src
  other-modules: []
tests:
  lib2-doctests:
    main: Main.hs
    source-dirs: test
    dependencies:
      - lib1
      - lib2
